
title: Unitarians in Thailand
url: 'http://www.thaiunitarians.org'

languages: ["en", "th"]
default_lang: "en"
exclude_from_localization: ["js", "images", "img", "css", "fonts"]
parallel_localization: true

plugins:
  - jekyll-polyglot
